Use one folder per test command

diff --git a/atddiff/test/generate-dune-rules b/atddiff/test/generate-dune-rules
--- a/atddiff/test/generate-dune-rules
+++ b/atddiff/test/generate-dune-rules
@@ -5,22 +5,28 @@
 #
 set -eu
 
-test_names=$(for x in *_old.atd; do echo $(basename "$x" _old.atd); done)
+generate_in_folder() {
+  # available variables: $folder, $atddiff_options
 
-cat > dune <<EOF
+  echo "Generating 'dune' file in $(pwd)"
+
+  shopt -s failglob
+  test_names=$(for x in *_old.atd; do echo $(basename "$x" _old.atd); done)
+
+  cat > dune <<EOF
 ; Generated by $0
 ; For adding tests, read the instructions in the Makefile.
 EOF
-for name in $test_names; do
-  if ! [[ -e "$name"_new.atd ]]; then
-    echo "Missing test file '${name}_new.atd'" >&2
-    exit 1
-  fi
-  cat >> dune <<EOF
+  for name in $test_names; do
+    if ! [[ -e "$name"_new.atd ]]; then
+      echo "Missing test file '${name}_new.atd'" >&2
+      exit 1
+    fi
+    cat >> dune <<EOF
 (rule
  (targets $name.txt)
  (deps ${name}_old.atd ${name}_new.atd)
- (action (run %{bin:atddiff} %{deps} -o %{targets})))
+ (action (run %{bin:atddiff} %{deps} -o %{targets} $atddiff_options)))
 
 (rule
  (alias runtest)
@@ -29,9 +35,34 @@ for name in $test_names; do
 
 EOF
 
-  # Create empty output files if they don't exist already so as to save
-  # some manual labor
-  if ! [[ -e "$name".expected.txt ]]; then
-    touch "$name".expected.txt
-  fi
+    # Create empty output files if they don't exist already so as to save
+    # some manual labor
+    if ! [[ -e "$name".expected.txt ]]; then
+      touch "$name".expected.txt
+    fi
+  done
+}
+
+folders="
+  default
+  json_defaults
+"
+
+for folder in $folders; do
+  atddiff_options=""
+  case "$folder" in
+    default)
+      ;;
+    json_defaults)
+      atddiff_options="--json-defaults"
+      ;;
+    *)
+      echo "Error: Unknown atddiff command for test folder $folder" >&2
+      exit 1
+      ;;
+  esac
+  (
+    cd "$folder"
+    generate_in_folder
+  )
 done
